version: '3.8'

services:

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: mtg_rabbitmq

    ports:
      - "5672:5672"
      - "15672:15672"

    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:16-alpine
    container_name: mtg_postgres

    restart: unless-stopped

    environment:
      POSTGRES_USER: mtg_user
      POSTGRES_PASSWORD: change_me
      POSTGRES_DB: usage_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: